name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/flexnow-notifications"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/flexnow-notifications

            docker build --build-arg GIT_REVISION=$(git rev-parse HEAD) -t flexnow-notifications:latest .

            if [ $(docker ps -q -f name=flexnow-notifications) ]; then
              docker stop flexnow-notifications
              docker rm flexnow-notifications
            fi

            if [ ! $(docker info --format '{{.Swarm.LocalNodeState}}') == "active" ]; then
              docker swarm init
            fi

            echo "${{ secrets.APP_USERNAME }}" | docker secret create APP_USERNAME || true
            echo "${{ secrets.APP_PASSWORD }}" | docker secret create APP_PASSWORD || true

            docker service create \
              --name flexnow-notifications \
              --secret APP_USERNAME \
              --secret APP_PASSWORD \
              --restart-condition any \
              --detach=true \
              flexnow-notifications:latest

            if [ $(docker service ls --filter name=flexnow-notifications -q) ]; then
              docker service update --force \
                --secret-rm APP_USERNAME \
                --secret-rm APP_PASSWORD \
                --secret-add APP_USERNAME \
                --secret-add APP_PASSWORD \
                --image flexnow-notifications:latest flexnow-notifications
            else
              docker service create \
                --name flexnow-notifications \
                --secret APP_USERNAME \
                --secret APP_PASSWORD \
                --restart-condition any \
                --detach=true \
                flexnow-notifications:latest
            fi
