name: Deploy

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v2

      # Build and push Docker image with secrets
      - name: Build and push the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./path/to/Dockerfile # Pfad zu deinem Dockerfile
          platforms: linux/amd64
          tags: my.private.registry.com/my-image:latest
          secrets: |
            "APP_USERNAME=${{ secrets.APP_USERNAME }}"
            "APP_PASSWORD=${{ secrets.APP_PASSWORD }}"

      # Connect via SSH to execute additional remote commands
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull my.private.registry.com/my-image:latest
            docker stop flexnow-notifications || true
            docker rm flexnow-notifications || true

            # Starte den neuen Container mit den Secrets
            docker run -d \
              --name flexnow-notifications \
              --restart unless-stopped \
              my.private.registry.com/my-image:latest
