name: Deploy

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v1

      # Copy repository contents to the VPS via SCP
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/flexnow-notifications"

      # Execute remote commands via SSH to build and deploy the Docker container
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/flexnow-notifications

            # Baue das Docker-Image basierend auf der Dockerfile im Repository
            docker build --build-arg GIT_REVISION=$(git rev-parse HEAD) -t flexnow-notifications:latest .

            # Stoppe und entferne den laufenden Container, falls er existiert
            if [ $(docker ps -q -f name=flexnow-notifications) ]; then
              docker stop flexnow-notifications
              docker rm flexnow-notifications
            fi

            # Falls Docker Swarm nicht läuft, initialisiere es
            if [ ! $(docker info --format '{{.Swarm.LocalNodeState}}') == "active" ]; then
              docker swarm init
            fi

            # Alte Docker Secrets entfernen, falls sie bereits existieren
            if [ $(docker secret ls | grep APP_USERNAME) ]; then
              docker secret rm APP_USERNAME
            fi
            if [ $(docker secret ls | grep APP_PASSWORD) ]; then
              docker secret rm APP_PASSWORD
            fi

            # Secrets mit den GitHub Secrets erstellen
            echo -n "${{ secrets.APP_USERNAME }}" | docker secret create APP_USERNAME
            echo -n "${{ secrets.APP_PASSWORD }}" | docker secret create APP_PASSWORD

            # Starte den neuen Service mit Docker Secrets
            docker service create \
              --name flexnow-notifications \
              --secret APP_USERNAME \
              --secret APP_PASSWORD \
              --restart-condition any \
              --detach=true \
              flexnow-notifications:latest
